---
repos:
  - repo: local
    hooks:
      # --- Formatters / style ---
      - id: black
        name: black
        entry: env PYTHONPATH=. pipenv run black
        language: system
        types: [python]
        args: ["--line-length=120"]

      - id: isort
        name: isort
        entry: env PYTHONPATH=. pipenv run isort
        language: system
        types: [python]
        args: ["--profile", "black"]

      - id: flake8
        name: flake8
        entry: env PYTHONPATH=. pipenv run flake8
        language: system
        types: [python]

      - id: pydocstyle
        name: pydocstyle
        entry: env PYTHONPATH=. pipenv run pydocstyle
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: env PYTHONPATH=. pipenv run pylint
        language: system
        pass_filenames: false
        args: ["ld_common", "tests"]

      - id: yamllint
        name: yamllint
        entry: env PYTHONPATH=. pipenv run yamllint
        language: system
        pass_filenames: false
        args: ["-s", ".pre-commit-config.yaml", ".yamllint.yaml"]

      - id: docktor-lint
        name: Lint Dockerfile with docktor-py
        entry: env PYTHONPATH=. pipenv run docktor lint Dockerfile
        language: system
        pass_filenames: false

      # # --- Type checking ---
      # - id: pyre
      #   name: pyre type check
      #   entry: env PYTHONPATH=. pipenv run python -m pyre_check.client.pyre check
      #   language: system
      #   pass_filenames: false

      # --- Security / quality gates ---
      - id: bandit
        name: bandit
        entry: env PYTHONPATH=. pipenv run bandit
        language: system
        pass_filenames: false
        args: ["-q", "-r", "ld_common", "-x", "tests"]

      - id: detect-secrets
        name: detect-secrets
        entry: env PYTHONPATH=. pipenv run detect-secrets-hook
        language: system
        pass_filenames: false

      - id: pip-audit
        name: pip-audit
        entry: env PYTHONPATH=. pipenv run pip-audit
        language: system
        pass_filenames: false

      - id: codespell
        name: codespell
        entry: env PYTHONPATH=. pipenv run codespell
        language: system
        args: ["-S share/*", "-x Pipfile.lock"]

      # --- Tests / runners ---
      - id: pytest
        name: pytest
        entry: env PYTHONPATH=. pipenv run pytest -v --no-cov
        language: system
        pass_filenames: false
