---
repos:
  - repo: local
    hooks:
      # --- Formatters / style ---
      - id: black
        name: black
        entry: pipenv run black
        language: system
        types: [python]
        args: ["--line-length=120"]

      - id: isort
        name: isort
        entry: pipenv run isort
        language: system
        types: [python]
        args: ["--profile", "black"]

      - id: flake8
        name: flake8
        entry: pipenv run flake8
        language: system
        types: [python]

      - id: pydocstyle
        name: pydocstyle
        entry: pipenv run pydocstyle
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: pipenv run pylint
        language: system
        pass_filenames: false
        args: ["bin"]

      - id: yamllint
        name: yamllint
        entry: pipenv run yamllint
        language: system
        pass_filenames: false
        args: ["-s", ".pre-commit-config.yaml", ".yamllint.yaml"]

      # --- Security / quality gates ---
      - id: bandit
        name: bandit
        entry: pipenv run bandit
        language: system
        pass_filenames: false
        args: ["-q", "-r", "ld_common", "-x", "tests"]

      - id: detect-secrets
        name: detect-secrets
        entry: pipenv run detect-secrets-hook
        language: system
        pass_filenames: false

      - id: pip-audit
        name: pip-audit
        entry: pipenv run pip-audit
        language: system
        pass_filenames: false

      - id: codespell
        name: codespell
        entry: pipenv run codespell
        language: system
        args: ["-x Pipfile.lock"]

      # --- Tests / runners ---
      - id: pytest
        name: pytest
        entry: pipenv run pytest -v --no-cov
        language: system
        pass_filenames: false
