name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Set up Python 3.13.7
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.13.7

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run pre-commit hooks
        run: pipenv run pre-commit run --all-files
