name: upgrade-main

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 14 * * *'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13.7'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv install --dev
      - name: Update Deps
        run: |
          pipenv update
          pre-commit run --all-files
          git diff
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.P6_PGOLLUCCI_GH_TOKEN }}
          commit-message: |-
            chore(deps): upgrade dependencies

            Upgrades project dependencies. See details in [workflow run].

            [Workflow Run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: github-actions/upgrade-main
          title: "chore(deps): upgrade dependencies"
          labels: auto-approve
          body: |-
            Upgrades project dependencies. See details in [workflow run].

            [Workflow Run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          author: github-actions <github-actions@github.com>
          committer: github-actions <github-actions@github.com>
          signoff: true
